name: Deploy to Server

# 触发条件：当有代码推送到 main 分支时
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 虚拟机环境

    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}             # 服务器 IP
        username: ${{ secrets.SSH_USERNAME }}       # 服务器用户名
        key: ${{ secrets.SSH_PRIVATE_KEY }}        # 服务器私钥
        # port: 22

        script: |
          # 1. 进入你的项目目录
          cd ${{ secrets.REMOTE_TARGET_DIR }}

          # 2. 清理本地更改，以远程仓库为准
          git config --global --add safe.directory ${{ secrets.REMOTE_TARGET_DIR }}
          git fetch origin
          git reset --hard origin/main
          git clean -fd

          # 3. 设置 Node.js 的 PATH 环境变量
          export PATH="/root/.nvm/versions/node/v22.16.0/bin:$PATH"

          # 4. 安装依赖（使用 npm ci 进行快速、可靠的安装）
          npm ci

          # 5. 重新构建 Next.js 项目
          npm run build

          # 6. 使用 PM2 重启服务
          pm2 reload suit